### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by eshanks16** [rubrikinc/vRO-Workflow#1]
I see a list of javascript files that look like they could be added as custom actions.
However, I don't see a package file that could be imported into vRO. Was that the intent? The README states that there is a package file to import.

**Comment by mattaltimar** [comment]
@eshanks16 The package com.rubrik.library.rest.package should be under releases.  Let me know if you don't see it there

**Comment by eshanks16** [comment]
There it is. I didn't see it in code. Got it now. Thanks. Nice work, by the way.
