### ISSUE TITLE
Package missing

### ISSUE THREAD

**Issue by eshanks16** [rubrikinc/vRO-Workflow#2]
Should the package files that are in the release be put into the project so that they can be submitted by other users later?

**Comment by mattaltimar** [comment]
I'd say that's fair.  I've updated the project with the package file.

Thanks,

Matt

**Comment by mattaltimar** [comment]
I posted the .package file to the project.  Are you ok with me closing this issue now or were you looking for something else?  I'm very new to github, so please excuse me if I misunderstood this

**Comment by eshanks16** [comment]
close it.
